<a href="https://colab.research.google.com/github/JonatanPolanco/Content_Classification/blob/main/Text_embedding_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

based on https://machinelearningmastery.com/use-word-embedding-layers-deep-learning-keras/

In [ ]:
!pip install -U sentence-transformers

In [ ]:
from numpy import array
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import Embedding

In [ ]:
#Data
reviews = ['good food',
		'amazing restaurant',
		'too good',
		'just loved it!',
		'will go again',
		'horrible food',
		'never go there',
		'poor service',
		'poor quality',
		'could have done better.']

# define class
sentiment = array([1,1,1,1,1,0,0,0,0,0])

In [ ]:
t = Tokenizer()
t.fit_on_texts(reviews)
vocab_size = 130
encoded_reviews = [one_hot(d,vocab_size) for d in reviews]
encoded_reviews

[[71, 52],
 [4, 26],
 [23, 71],
 [35, 65, 89],
 [94, 120, 15],
 [117, 52],
 [114, 120, 99],
 [15, 14],
 [15, 59],
 [109, 12, 39, 129]]

In [ ]:
max_length = 4
padded_reviews = pad_sequences(encoded_reviews,maxlen=max_length, padding='post')
padded_reviews

array([[ 71,  52,   0,   0],
       [  4,  26,   0,   0],
       [ 23,  71,   0,   0],
       [ 35,  65,  89,   0],
       [ 94, 120,  15,   0],
       [117,  52,   0,   0],
       [114, 120,  99,   0],
       [ 15,  14,   0,   0],
       [ 15,  59,   0,   0],
       [109,  12,  39, 129]], dtype=int32)

In [ ]:
embedded_vector_size = 100
model= Sequential()
model.add(Embedding(vocab_size, embedded_vector_size, input_length=max_length, name="embedding"))
model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))

In [ ]:
x= padded_reviews
y = sentiment

In [ ]:
model.compile(optimizer='adam', loss= 'binary_crossentropy', metrics= ['accuracy'])
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 100)            13000     
                                                                 
 flatten_2 (Flatten)         (None, 400)               0         
                                                                 
 dense_2 (Dense)             (None, 1)                 401       
                                                                 
Total params: 13401 (52.35 KB)
Trainable params: 13401 (52.35 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.fit(x,y,epochs=50, verbose=0)

In [ ]:
loss,accuracy= model.evaluate(x,y)
print('Accuracy: %f' % (accuracy*100))

1/1 [==============================] - 0s 172ms/step - loss: 0.3228 - accuracy: 1.0000
Accuracy: 100.000000


In [ ]:
weights= model.get_layer('embedding').get_weights()[0]
len(weights)

130

In [ ]:
weights[117]

array([ 0.08349814, -0.05257966, -0.05788439,  0.04783811, -0.06385551,
        0.05785656,  0.05388582,  0.10341027, -0.05280482, -0.00130491,
       -0.07161933, -0.01659988,  0.0175749 ,  0.09786219, -0.08276951,
        0.08516009,  0.09092549,  0.07642715, -0.06017594, -0.07666586,
        0.04959184,  0.02287739, -0.07632209,  0.00943629, -0.09266154,
        0.0206752 , -0.05855923,  0.0798265 , -0.06334135, -0.03347407,
        0.06295931, -0.01566822,  0.00019928, -0.03788371,  0.09934629,
        0.00171272, -0.0917448 , -0.1003641 ,  0.07003972,  0.03741294,
       -0.00238982, -0.01119515, -0.02199811, -0.04890532, -0.05737294,
       -0.08713874, -0.03533809,  0.08034632,  0.07473619, -0.03410041,
       -0.04594469,  0.04102343,  0.06892746, -0.10049187,  0.08447859,
        0.02160194,  0.05292599, -0.03180389,  0.10217924, -0.01368782,
        0.01496177, -0.05330318, -0.03477738,  0.06099873, -0.05956981,
        0.06674169, -0.06842321, -0.00762468,  0.01287811,  0.01

In [ ]:
weights[114]

array([ 0.07052068, -0.07375976, -0.06692451,  0.03569016, -0.03397086,
        0.03864356,  0.03883489,  0.07856889, -0.04743697, -0.03426807,
       -0.07867155, -0.00217061,  0.0986209 ,  0.06580832, -0.10195778,
        0.09111097,  0.04068038,  0.05990468, -0.06213154, -0.00328017,
        0.07399171,  0.08337041, -0.08746962,  0.06537665, -0.04680556,
        0.06662856, -0.05063967,  0.04956407, -0.09207786, -0.06721056,
        0.09953929, -0.0388265 , -0.05196716, -0.05619882,  0.08841241,
        0.0278171 , -0.00806591, -0.04265732,  0.03096014,  0.02476937,
       -0.01238192, -0.02893149, -0.07998466, -0.08088823, -0.07731205,
       -0.09628879, -0.06588861,  0.06089277,  0.00993542,  0.0222324 ,
       -0.03345624,  0.07342292,  0.00267123, -0.04261241,  0.02395613,
        0.06772646,  0.07112404, -0.00341054,  0.07334675, -0.03100235,
        0.08003385, -0.02020354, -0.03562322,  0.00278389, -0.10317554,
        0.07803485, -0.05386138, -0.07368977,  0.04129495,  0.05

In [ ]:
from scipy.spatial.distance import cosine
1-cosine(weights[117], weights[114])


0.8014395833015442

Based on https://github.com/PradipNichite/Youtube-Tutorials/blob/main/Youtube_Course_Sentence_Transformers.ipynb

https://www.youtube.com/watch?v=OlhNZg4gOvA

In [ ]:
from sentence_transformers import SentenceTransformer,util
model = SentenceTransformer('all-MiniLM-L6-v2')

In [ ]:
sentences = ['A man is eating food.',
          'A man is eating a piece of bread.',
          'The girl is carrying a baby.',
          'A man is riding a horse.',
          'A woman is playing violin.',
          'Two men pushed carts through the woods.',
          'A man is riding a white horse on an enclosed ground.',
          'A monkey is playing drums.',
          'Someone in a gorilla costume is playing a set of drums.'
          ]

#Encode all sentences
embeddings = model.encode(sentences)

#Compute cosine similarity between all pairs
cos_sim = util.cos_sim(embeddings, embeddings)

cos_sim

tensor([[ 1.0000,  0.7553, -0.1050,  0.2474, -0.0704, -0.0333,  0.1707,  0.0476,
          0.0630],
        [ 0.7553,  1.0000, -0.0610,  0.1442, -0.0809, -0.0216,  0.1157,  0.0362,
          0.0216],
        [-0.1050, -0.0610,  1.0000, -0.1088,  0.0217, -0.0413, -0.0928,  0.0231,
          0.0247],
        [ 0.2474,  0.1442, -0.1088,  1.0000, -0.0348,  0.0362,  0.7369,  0.0821,
          0.1389],
        [-0.0704, -0.0809,  0.0217, -0.0348,  1.0000, -0.1654, -0.0592,  0.1961,
          0.2564],
        [-0.0333, -0.0216, -0.0413,  0.0362, -0.1654,  1.0000,  0.0769, -0.0380,
         -0.0895],
        [ 0.1707,  0.1157, -0.0928,  0.7369, -0.0592,  0.0769,  1.0000,  0.0495,
          0.1191],
        [ 0.0476,  0.0362,  0.0231,  0.0821,  0.1961, -0.0380,  0.0495,  1.0000,
          0.6433],
        [ 0.0630,  0.0216,  0.0247,  0.1389,  0.2564, -0.0895,  0.1191,  0.6433,
          1.0000]])

In [ ]:
embeddings[1]

array([ 5.25184199e-02,  5.52413054e-02, -1.11882035e-02, -5.74539369e-03,
       -1.27208263e-01, -2.22518295e-02,  7.68786594e-02,  1.31851463e-02,
       -2.54259203e-02,  6.55381754e-02, -1.67244542e-02, -4.14088853e-02,
       -8.71009529e-02, -3.97862010e-02,  4.49407031e-04, -5.87471537e-02,
        8.69543999e-02,  1.79728232e-02,  6.68900609e-02,  4.26590629e-03,
        6.96159750e-02,  8.58952105e-02,  3.43692154e-02, -4.27250452e-02,
        9.67469998e-03, -1.49257807e-02,  1.12933643e-01, -5.82889095e-02,
       -7.23475078e-03, -3.63896526e-02,  7.91820288e-02, -5.31536341e-03,
        3.48646678e-02, -3.00621446e-02, -5.00721261e-02, -4.93985675e-02,
        9.21830013e-02, -2.92388368e-02,  4.31469716e-02, -1.43452985e-02,
        1.46957748e-02, -6.34765439e-03, -8.00972153e-03,  7.64189065e-02,
       -3.97982299e-02,  3.23388465e-02, -4.89241108e-02,  3.78988832e-02,
        1.72386542e-02, -2.70875953e-02, -5.47547750e-02,  2.77214334e-03,
        3.52052003e-02,  

In [ ]:
#Add all pairs to a list with their cosine similarity score
all_sentence_combinations = []
for i in range(len(cos_sim)-1):
    for j in range(i+1, len(cos_sim)):
        all_sentence_combinations.append((cos_sim[i][j], i, j))
all_sentence_combinations

[(tensor(0.7553), 0, 1),
 (tensor(-0.1050), 0, 2),
 (tensor(0.2474), 0, 3),
 (tensor(-0.0704), 0, 4),
 (tensor(-0.0333), 0, 5),
 (tensor(0.1707), 0, 6),
 (tensor(0.0476), 0, 7),
 (tensor(0.0630), 0, 8),
 (tensor(-0.0610), 1, 2),
 (tensor(0.1442), 1, 3),
 (tensor(-0.0809), 1, 4),
 (tensor(-0.0216), 1, 5),
 (tensor(0.1157), 1, 6),
 (tensor(0.0362), 1, 7),
 (tensor(0.0216), 1, 8),
 (tensor(-0.1088), 2, 3),
 (tensor(0.0217), 2, 4),
 (tensor(-0.0413), 2, 5),
 (tensor(-0.0928), 2, 6),
 (tensor(0.0231), 2, 7),
 (tensor(0.0247), 2, 8),
 (tensor(-0.0348), 3, 4),
 (tensor(0.0362), 3, 5),
 (tensor(0.7369), 3, 6),
 (tensor(0.0821), 3, 7),
 (tensor(0.1389), 3, 8),
 (tensor(-0.1654), 4, 5),
 (tensor(-0.0592), 4, 6),
 (tensor(0.1961), 4, 7),
 (tensor(0.2564), 4, 8),
 (tensor(0.0769), 5, 6),
 (tensor(-0.0380), 5, 7),
 (tensor(-0.0895), 5, 8),
 (tensor(0.0495), 6, 7),
 (tensor(0.1191), 6, 8),
 (tensor(0.6433), 7, 8)]

In [ ]:

#Sort list by the highest cosine similarity score
all_sentence_combinations = sorted(all_sentence_combinations, key=lambda x: x[0], reverse=True)

print("Top-5 most similar pairs:")
for score, i, j in all_sentence_combinations[0:5]:
    print("{} \t {} \t {:.4f}".format(sentences[i], sentences[j], cos_sim[i][j]))

Top-5 most similar pairs:
A man is eating food. 	 A man is eating a piece of bread. 	 0.7553
A man is riding a horse. 	 A man is riding a white horse on an enclosed ground. 	 0.7369
A monkey is playing drums. 	 Someone in a gorilla costume is playing a set of drums. 	 0.6433
A woman is playing violin. 	 Someone in a gorilla costume is playing a set of drums. 	 0.2564
A man is eating food. 	 A man is riding a horse. 	 0.2474


Clustering

In [ ]:
from sklearn.cluster import KMeans
import numpy as np

embedder = SentenceTransformer('all-MiniLM-L6-v2')

# Corpus with example sentences
corpus = ['A man is eating food.',
          'A man is eating a piece of bread.',
          'Horse is eating grass.',
          'A man is eating pasta.',
          'A Woman is eating Biryani.',
          'The girl is carrying a baby.',
          'The baby is carried by the woman',
          'A man is riding a horse.',
          'A man is riding a white horse on an enclosed ground.',
          'A monkey is playing drums.',
          'Someone in a gorilla costume is playing a set of drums.',
          'A cheetah is running behind its prey.',
          'A cheetah chases prey on across a field.',
          'The cheetah is chasing a man who is riding the horse.',
          'man and women with their baby are watching cheetah in zoo'
          ]
corpus_embeddings = embedder.encode(corpus)

# Normalize the embeddings to unit length
corpus_embeddings = corpus_embeddings /  np.linalg.norm(corpus_embeddings, axis=1, keepdims=True)

In [ ]:
corpus_embeddings[0]

array([ 3.32415923e-02,  4.40611131e-03, -6.27698097e-03,  4.83787395e-02,
       -1.38702288e-01, -3.36174108e-02,  1.01128370e-01, -5.43849692e-02,
       -4.32477817e-02, -3.99411246e-02,  7.78633682e-03, -1.27489287e-02,
       -6.68302402e-02, -1.73865426e-02,  4.74506281e-02, -5.77242412e-02,
        1.01888366e-01, -9.11662937e-04,  8.22615027e-02, -5.03415726e-02,
        6.77302927e-02,  4.08765152e-02, -3.58018912e-02, -1.00682415e-01,
       -6.69354713e-03, -5.31686284e-02,  1.00335158e-01, -5.46135865e-02,
       -2.28481367e-02,  1.38387140e-02,  7.48658478e-02, -6.17880039e-02,
        6.39215931e-02,  1.62387323e-02, -5.32299615e-02, -3.86084318e-02,
        3.15275863e-02, -8.11529905e-02, -3.31432372e-02, -5.38505905e-04,
       -3.96069745e-03, -1.52734164e-02, -9.86421946e-04,  9.57987979e-02,
       -5.42920306e-02,  1.84572097e-02, -1.07143618e-01,  1.38884904e-02,
        3.94072384e-02, -2.69243568e-02, -9.15988758e-02, -1.14195142e-02,
        3.38137113e-02, -

In [ ]:
# source: https://stackoverflow.com/questions/55619176/how-to-cluster-similar-sentences-using-bert

clustering_model = KMeans(n_clusters=4)
clustering_model.fit(corpus_embeddings)
cluster_assignment = clustering_model.labels_
print(cluster_assignment)

[3 3 1 3 3 2 2 1 1 0 0 1 1 1 2]


/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


In [ ]:
clustered_sentences = {}
for sentence_id, cluster_id in enumerate(cluster_assignment):
    if cluster_id not in clustered_sentences:
        clustered_sentences[cluster_id] = []

    clustered_sentences[cluster_id].append(corpus[sentence_id])
clustered_sentences

{3: ['A man is eating food.',
  'A man is eating a piece of bread.',
  'A man is eating pasta.',
  'A Woman is eating Biryani.'],
 1: ['Horse is eating grass.',
  'A man is riding a horse.',
  'A man is riding a white horse on an enclosed ground.',
  'A cheetah is running behind its prey.',
  'A cheetah chases prey on across a field.',
  'The cheetah is chasing a man who is riding the horse.'],
 2: ['The girl is carrying a baby.',
  'The baby is carried by the woman',
  'man and women with their baby are watching cheetah in zoo'],
 0: ['A monkey is playing drums.',
  'Someone in a gorilla costume is playing a set of drums.']}

Classification based on https://spotintelligence.com/2023/02/15/word2vec-for-text-classification/

In [ ]:
!wget https://s3.amazonaws.com/arrival/embeddings/wiki.multi.en.vec -O /tmp/wiki.multi.en.vec
!wget https://s3.amazonaws.com/arrival/embeddings/wiki.multi.fr.vec -O /tmp/wiki.multi.fr.vec

--2024-01-25 15:50:17--  https://s3.amazonaws.com/arrival/embeddings/wiki.multi.en.vec
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.217.125.128, 54.231.160.104, 52.217.121.64, ...
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.217.125.128|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: unspecified
ERROR: Redirection (301) without location.
--2024-01-25 15:50:17--  https://s3.amazonaws.com/arrival/embeddings/wiki.multi.fr.vec
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.217.125.128, 54.231.160.104, 52.217.121.64, ...
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.217.125.128|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: unspecified
ERROR: Redirection (301) without location.


In [ ]:
import pandas as pd
url1 = 'https://raw.githubusercontent.com/LinaAguilar0697/content_classification/main/Notebooks/competence_definitions.csv'
url2 = 'https://raw.githubusercontent.com/LinaAguilar0697/content_classification/main/Notebooks/content_gsheet_info.csv'

competence_definitions = pd.read_csv(url1)
contents_to_clasify  = pd.read_csv(url2)

In [ ]:
competence_definitions.head()

id_competence              competence  \
0            1.0          Accountability   
1            1.0          Accountability   
2            1.0          Accountability   
3            2.0  Inteligencia emocional   
4            2.0  Inteligencia emocional   

                               competence_definition  id_skill  \
0  Una persona demuestra su accountability cuando...       1.0   
1  Una persona demuestra su accountability cuando...       2.0   
2  Una persona demuestra su accountability cuando...       3.0   
3  Una persona demuestra su inteligencia emociona...       4.0   
4  Una persona demuestra su inteligencia emociona...       5.0   

            ability                                 ability_definition  \
0       Autogestión  Habilidad para orientar la toma de decisiones ...   
1      Proactividad  Habilidad para tomar activamente el control y ...   
2        Integridad  Habilidad para alinear las acciones propias a ...   
3           Empatía  Habilidad para identificarse con el otro recon...   
4  Autoconocimiento  Habilidad para reconocer los propios estados m...   

                                    course_abilities  
0  Autogestión: \nHabilidad para orientar la toma...  
1  Proactividad: \nHabilidad para tomar activamen...  
2  Integridad: \nHabilidad para alinear las accio...  
3  Empatía: \nHabilidad para identificarse con el...  
4  Autoconocimiento: \nHabilidad para reconocer l...

In [ ]:
contents_to_clasify

<!DOCTYPE html>
0                                                 <html
1                                             lang="en"
2       data-color-mode="auto" data-light-theme="lig...
3       data-a11y-animated-images="system" data-a11y...
4                                                     >
...                                                 ...
1045                                             </div>
1046      <div id="js-global-screen-reader-notice" c...
1047      <div id="js-global-screen-reader-notice-as...
1048                                            </body>
1049                                            </html>

[1050 rows x 1 columns]

In [ ]:
import numpy as np

def load_vectors(embedding_file_path):
    print("Loading vectors from", embedding_file_path)
    embeddings = []
    word2id = {}
    with open(embedding_file_path, 'r', encoding='utf-8') as f:
        next(f)
        for i, line in enumerate(f):
            word, emb = line.rstrip().split(' ', 1)
            emb = np.fromstring(emb, sep=' ')
            assert word not in word2id, 'word found twice'
            embeddings.append(emb)
            word2id[word] = len(word2id)

    embeddings = np.vstack(embeddings)
    return embeddings, word2id

embeddings_en, embedding_word2id_en = load_vectors("/tmp/wiki.multi.en.vec")
embeddings_fr, embedding_word2id_fr = load_vectors("/tmp/wiki.multi.fr.vec")